### ISSUE TITLE
Aktuelles Gartner Hypecycle-Diagramm für 5200_IoT/03_Datenübertragung.html

### ISSUE THREAD

**Issue by sedot42** [314a/5200_IoT#1]
Das Diagramm im Dokument ist von 2023. Es ist bereits ein neues verfügbar:  https://www.gartner.com/en/newsroom/press-releases/2024-08-21-gartner-2024-hype-cycle-for-emerging-technologies-highlights-developer-productivity-total-experience-ai-and-security

**Comment by 314a** [comment]
Super, danke für den Link, dann haben sich die Aktualisierung und die Publikation gekreuzt.
